### ISSUE TITLE
AttributeError: 'ZappaCLI' object has no attribute 'apigateway_policy'

### ISSUE THREAD

**Issue by rajdotnet** [Miserlou/Zappa#1747]
zappa template dev --l your-lambda-arn -r your-role-arn cli command gives AttributeError: 'ZappaCLI' object has no attribute 'apigateway_policy' error in version 0.47.1
## Context

This command works fine in version 0.47.0

## Expected Behavior
the zappa template command should work and generate cloudfromation template in version 0.47.0 instead of erroring out

## Actual Behavior
Calling template for stage dev..
Oh no! An error occurred! :(

==============

Traceback (most recent call last):
  File "c:\program files (x86)\python36-32\lib\site-packages\zappa\cli.py", line 2712, in handle
    sys.exit(cli.handle())
  File "c:\program files (x86)\python36-32\lib\site-packages\zappa\cli.py", line 509, in handle
    self.dispatch_command(self.command, stage)
  File "c:\program files (x86)\python36-32\lib\site-packages\zappa\cli.py", line 553, in dispatch_command
    json=self.vargs['json']
  File "c:\program files (x86)\python36-32\lib\site-packages\zappa\cli.py", line 666, in template
    policy=self.apigateway_policy
AttributeError: 'ZappaCLI' object has no attribute 'apigateway_policy'

## Steps to Reproduce

1. run zappa init
2. run zappa template dev --l your-lambda-arn -r your-role-arn
3.

## Your Environment

* Zappa version used: 0.47.1
* Operating System and Python version: Windows 10 python version 3.6.4
* The output of `pip freeze`:
argcomplete==1.9.3
arrow==0.12.1
astroid==2.0.4
aws-lambda-builders==0.0.4
aws-sam-cli==0.9.0
aws-sam-translator==1.9.0
binaryornot==0.4.4
boto3==1.9.67
botocore==1.12.67
certifi==2018.10.15
cfn-flip==1.0.3
chardet==3.0.4
chevron==0.13.1
click==6.7
colorama==0.3.9
cookiecutter==1.6.0
dateparser==0.7.0
docker==3.6.0
docker-pycreds==0.4.0
docutils==0.14
durationpy==0.5
Flask==1.0.2
future==0.16.0
hjson==3.0.1
idna==2.7
isort==4.3.4
itsdangerous==1.1.0
Jinja2==2.10
jinja2-time==0.2.0
jmespath==0.9.3
jsonschema==2.6.0
kappa==0.6.0
lambda-packages==0.20.0
lazy-object-proxy==1.3.1
MarkupSafe==1.1.0
mccabe==0.6.1
placebo==0.8.2
poyo==0.4.2
pylint==2.1.1
pypiwin32==223
python-dateutil==2.6.1
python-slugify==1.2.4
pytz==2018.7
pywin32==224
PyYAML==3.13
regex==2018.11.22
requests==2.20.0
s3transfer==0.1.13
six==1.11.0
toml==0.10.0
tqdm==4.19.1
troposphere==2.3.3
typed-ast==1.1.0
tzlocal==1.5.1
Unidecode==1.0.22
urllib3==1.24
virtualenv==16.0.0
websocket-client==0.54.0
Werkzeug==0.14.1
whichcraft==0.5.2
wrapt==1.10.11
wsgi-request-logger==0.4.6
zappa==0.47.1
* Link to your project (optional):
* Your `zappa_settings.py`: 
{
    "dev": {
        "app_function": "app.app",
        "aws_region": "us-east-1",
        "profile_name": "dev",
        "project_name": "ex-zappa",
        "runtime": "python3.6",
        "s3_bucket": "zappa-sample-flask-lambda"
    }
}

**Comment by rinckemd** [comment]
Just hit this on 0.48.2 which I wanted for python 3.7 support.  Not sure the correct fix, but I had to fork and hack out the policy argument to get around it.

**Comment by gregorypierce** [comment]
This defect is still around. Basically kills the ability to upgrade properly. I went through in the cli.py files and did the following:

        # Create the template!
        template = self.zappa.create_stack_template(
                                            lambda_arn=lambda_arn,
                                            lambda_name=self.lambda_name,
                                            api_key_required=self.api_key_required,
                                            iam_authorization=self.iam_authorization,
                                            authorizer=self.authorizer,
                                            cors_options=self.cors,
                                            description=self.apigateway_description,
                                            #policy=self.apigateway_policy
                                        )

Let's you move forward.

**Comment by mikehallishere** [comment]
Affecting us too. Please put in a fix.
