### ISSUE TITLE
django project showing empty page with zappa==0.22.2

### ISSUE THREAD

**Issue by michaelluk** [Miserlou/Zappa#296]
I've got empty webpage showing after update to 0.22.2, with the same symptoms as #262, except I was trying to deploy a django project. I was able to deploy successfully with the previous version.

This is the error message:
`[1472715319652] 'module' object has no attribute 'setup'`

Is anyone facing the same problem?
Thanks :)

**Comment by koriaf** [comment]
Got the same; may be helpful to install Zappa from github (`pip install git+https://github.com/Miserlou/Zappa.git --upgrade`)

**Comment by Miserlou** [comment]
Damn, it seems like this issue only occurs in the pip version. What an annoying bug.

A temporary work around is to use a local repo: https://github.com/Miserlou/Zappa#using-a-local-repo

Meanwhile, I will investigate.

**Comment by Miserlou** [comment]
This is a really annoying one.

'django.py' moved to 'django_zappa.py', but for some reason _both_ are included in the package on PyPI. I don't know why.

**Comment by Miserlou** [comment]
I've pushed a new version - 0.22.3 - can you try that now? I think it was just that random packaging error. I hope.

**Comment by michaelluk** [comment]
@Miserlou Yay, it works. Thanks for creating this project. Love it❤️

**Comment by Miserlou** [comment]
Okay, thank goodness. If that wasn't it, I would have gone crazy!

Thanks for using Zappa, sorry for letting this bug slip through!
