### ISSUE TITLE
How to pass kwargs to scheduled function?

### ISSUE THREAD

**Issue by trickidicki** [Miserlou/Zappa#1511]
I tried following the docs:

```
def myfun(event, context):
  try:
    args = event.get('kwargs')
    # do stuff
    return true
  except Exception, error:
    logging.error("myfun error: %s" % str(error))
    return false
```
 with unit test:
```
class MyTest(unittest.TestCase):
    def test_fun(self):
        event={}
        event['kwargs']={
            "arg1": "abc",
            "arg2": "123"
        }
        assert( myfn(event, context={}) )

```

But when I upload with Zappa I'm getting the following error message:
`>>zappa tail`

`myfun error: 'NoneType' object has no attribute '__getitem__'`

What's the correct way to pass kwargs? Thanks for your help.

**Comment by paulclarkaranz** [comment]
From [the code](https://github.com/Miserlou/Zappa/blob/master/zappa/core.py#L2325) it looks like you can add a `kwargs` key to the event definition in the config. That was introduced in 3fca9cc0dace0 which... dose have docs, they are just in a more [generic section of the readme](https://github.com/Miserlou/Zappa#executing-in-response-to-aws-events).

**Comment by trickidicki** [comment]
Thanks for the reply @paulclarkaranz, that's the functionality I'm trying to use.  The docs say:
```def your_recurring_function(event, context):
    my_kwargs = event.get(kwargs)  # dict of kwargs given in zappa_settings file
```

Is that a bug? Should it instead read:
```def your_recurring_function(event, context):
    my_kwargs = event.get('kwargs')  # dict of kwargs given in zappa_settings file
```
where `kwargs` is a string?
Thanks

**Comment by trickidicki** [comment]
I think the problem is that I'm using Python 2.7 and the kwargs string needs to be unicode.
So the code should read:
`my_kwargs = event.get(u'kwargs')  # dict of kwargs given in zappa_settings file`
